# Generated by Django 3.2.6 on 2021-08-09 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Typ', models.CharField(choices=[('Berge', 'Berg')], max_length=50)),
                ('Name', models.CharField(max_length=150)),
                ('Bezeichnung', models.TextField(max_length=500)),
                ('Bild', models.ImageField(upload_to='photos')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
